#define MAX_ITEM_BUFFERS    8
#define ITEM_BUFFER_LENGTH  20



typedef enum
{
    SHED,
    END_SHED,
    REQUEST_POWER_LEVEL,
    PRESENT_RELATIVE_PRICE,
    NEXT_PERIOD_RELATIVE_PRICE,
    TIME_IN_PRICE_PERIOD,
    CRITICAL_PEAK_EVENT,
    GRID_EMERGENCY,
    GRID_GUIDANCE,
    LOAD_UP,
    REQ_OP_STATE,
    OUTSIDE_COMM_GOOD,
    OUTSIDE_COMM_LOST,
    SIMPLE_TIME_SYNC,
    PENDING_EVENT,
    PENDING_EVENT_TYPE,
    GET_COMMODITY_READ,
    SET_COMMODITY_READ,
    START_AUTONOMOUS_CYCLING,
    TERMINATE_AUTONOMOUS_CYCLING,
    UNKNOWN_TYPE
            
} MCI_MESSAGE_TYPE;

typedef enum {
    FRESH,
    EVENT_IDENTIFIED,
    FAULT
}REST_PARSE_STATE;

extern MCI_MESSAGE_TYPE eventType;